version: '3.8'
services:
  db:
    image: mysql:8.0.27
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=harsh
      - MYSQL_DATABASE=GraphQL
      - MYSQL_USER=harsh
      - MYSQL_PASSWORD=harsh
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3308:3306'
volumes:
  db:
    driver: local

